// Default-Menü — wird verwendet wenn KV noch leer ist
// Wird automatisch durch Admin-Panel überschrieben

export const DEFAULT_MENU = [
  // ── Cheese Steak ──
  { id: 'cs1', cat: 'Cheese Steak', name: 'Chili Cheese Steak', desc: 'Z.B 180g Steak Fleisch, Jalapeño, gebratene Peperoni und Zwiebeln, Zutaten nach Wahl', price: 25.90, labels: ['scharf'] },
  { id: 'cs2', cat: 'Cheese Steak', name: 'Appenzeller Cheese Steak', desc: 'Z.B 180g Steak Fleisch, Jalapeño, gebratene Peperoni und Zwiebeln, Zutaten nach Wahl', price: 25.90, labels: [] },
  { id: 'cs3', cat: 'Cheese Steak', name: 'Cheese Steak', desc: 'Steak Fleisch, Jalapeño, gebratene Zwiebeln und Peperoni', price: 25.90, labels: ['beliebt'] },
  { id: 'cs4', cat: 'Cheese Steak', name: 'Raclette Cheese Steak', desc: 'Steak Fleisch, Jalapeño, gebratene Zwiebeln und Peperoni mit Raclettekäse', price: 25.90, labels: [] },
  // ── Kebab ──
  { id: 'k1',  cat: 'Kebab', name: 'Kebab', desc: 'Zubereitet mit Zutaten nach Wahl', price: 13.90, labels: ['beliebt'] },
  { id: 'k2',  cat: 'Kebab', name: 'Kebab Menü', desc: 'Taschenbrot mit Pommes und 330ml Soft-Getränk', price: 21.00, labels: ['beliebt'] },
  { id: 'k3',  cat: 'Kebab', name: 'Dürüm', desc: 'Zubereitet mit Zutaten nach Wahl', price: 13.90, labels: [] },
  { id: 'k4',  cat: 'Kebab', name: 'Dürüm Döner Kebab Menü', desc: 'Dürüm mit einer kleinen Portion Pommes und einer Dose Coca-Cola', price: 21.00, labels: [] },
  { id: 'k5',  cat: 'Kebab', name: 'Mega Dürüm', desc: 'Zubereitet mit Zutaten nach Wahl', price: 18.90, labels: [] },
  { id: 'k6',  cat: 'Kebab', name: 'XL Dürüm', desc: 'Zubereitet mit Zutaten nach Wahl', price: 24.90, labels: [] },
  { id: 'k7',  cat: 'Kebab', name: 'XXL Dürüm', desc: 'Zubereitet mit Zutaten nach Wahl', price: 28.90, labels: [] },
  { id: 'k8',  cat: 'Kebab', name: 'Kebab Poulet', desc: 'Zubereitet mit Poulet-Schichtfleisch und Zutaten nach Wahl', price: 13.90, labels: [] },
  { id: 'k9',  cat: 'Kebab', name: 'Dürüm Poulet', desc: 'Zubereitet mit Zutaten nach Wahl', price: 13.90, labels: [] },
  { id: 'k10', cat: 'Kebab', name: 'Hausgemachtes Schichtfleisch Kebab', desc: 'Hausgemachtes Schichtfleisch Kalp Flasch', price: 18.90, labels: ['beliebt'] },
  { id: 'k11', cat: 'Kebab', name: 'Appenzeller Dürüm', desc: 'Appenzeller Käse mit Rösti Patty', price: 20.00, labels: [] },
  { id: 'k12', cat: 'Kebab', name: 'Ufo Döner', desc: 'Zubereitet mit Ufo-geformten Teig und Zutaten nach Wahl', price: 15.90, labels: ['neu'] },
  { id: 'k13', cat: 'Kebab', name: 'Ufo Sucuk Kebab', desc: 'Zubereitet mit Ufo-geformten Teig und Zutaten nach Wahl', price: 16.90, labels: ['neu'] },
  { id: 'k14', cat: 'Kebab', name: 'Hausgemachte Köfte (5 Stk)', desc: 'Zubereitet mit Zutaten nach Wahl', price: 18.90, labels: [] },
  { id: 'k15', cat: 'Kebab', name: 'Döner Box klein', desc: 'Zubereitet mit Zutaten nach Wahl', price: 13.90, labels: [] },
  { id: 'k16', cat: 'Kebab', name: 'Kebab Box', desc: 'Zubereitet mit Zutaten nach Wahl', price: 15.90, labels: [] },
  { id: 'k17', cat: 'Kebab', name: 'Kebab Box XXL', desc: 'Z.B Pommes mit Fleisch', price: 20.00, labels: [] },
  { id: 'k18', cat: 'Kebab', name: 'Kebab Teller', desc: 'Zubereitet mit 200g Kebabfleisch, Salat und Pommes Frites', price: 22.00, labels: [] },
  { id: 'k19', cat: 'Kebab', name: 'Fladenbrot Kebab klein', desc: 'Zubereitet mit Zutaten nach Wahl', price: 12.90, labels: [] },
  { id: 'k20', cat: 'Kebab', name: 'Chef Dürüm', desc: 'Rindfleisch, Paprika, Zwiebeln, Tomaten, Petersilie, Zitronensaft und Sumach', price: 20.00, labels: ['beliebt'] },
  { id: 'k21', cat: 'Kebab', name: 'Avocado Dürüm', desc: 'Zubereitet mit Guacamole und Zutaten nach Wahl', price: 17.00, labels: ['neu'] },
  { id: 'k22', cat: 'Kebab', name: 'Kebab Raclette', desc: 'Dönerfleisch, Rösti Patty, Raclettekäse, Gurken und Zutaten nach Wahl', price: 20.00, labels: [] },
  { id: 'k23', cat: 'Kebab', name: 'Tantuni Kebab Kalb Dürüm', desc: 'Kalbfleisch, Tomaten, Zwiebeln, Petersilie, Zitronensaft, nach Wunsch scharf', price: 18.90, labels: ['scharf'] },
  { id: 'k24', cat: 'Kebab', name: 'Tantuni Kebab Poulet Dürüm', desc: 'Poulet, Tomaten, Zwiebeln, Petersilie, Zitronensaft, nach Wunsch scharf', price: 16.00, labels: ['scharf'] },
  { id: 'k25', cat: 'Kebab', name: 'Kebab mit Schafskäse', desc: 'Zubereitet mit Zutaten nach Wahl', price: 14.90, labels: [] },
  { id: 'k26', cat: 'Kebab', name: 'Kebab mit Spiegelei', desc: 'Zubereitet mit Zutaten nach Wahl', price: 15.00, labels: [] },
  { id: 'k27', cat: 'Kebab', name: 'Dürüm mit Schafskäse', desc: 'Zubereitet mit Zutaten nach Wahl', price: 15.00, labels: [] },
  { id: 'k28', cat: 'Kebab', name: 'Dürüm mit Spiegelei', desc: 'Zubereitet mit Zutaten nach Wahl', price: 15.00, labels: [] },
  // ── Tacos ──
  { id: 'ta1', cat: 'Tacos', name: 'Tacos Menü', desc: 'Tacos mit Pommes und 330ml Soft-Getränk', price: 24.00, labels: ['beliebt'] },
  { id: 'ta2', cat: 'Tacos', name: 'Wunsch Tacos', desc: 'Zutaten nach Wahl', price: 16.00, labels: [] },
  { id: 'ta3', cat: 'Tacos', name: 'Tacos Poulet', desc: 'Poulet, Mozzarella, Pommes Frites, Sauce nach Wahl', price: 16.00, labels: [] },
  { id: 'ta4', cat: 'Tacos', name: 'Tacos Lamm', desc: 'Lamm, Mozzarella, Pommes Frites, Sauce nach Wahl', price: 18.00, labels: [] },
  { id: 'ta5', cat: 'Tacos', name: 'Tacos Sucuk', desc: 'Sucuk, Mozzarella, Pommes Frites, Sauce nach Wahl', price: 16.00, labels: ['scharf'] },
  { id: 'ta6', cat: 'Tacos', name: 'Tacos Kalb', desc: 'Kalbfleisch, Mozzarella, Pommes Frites, Sauce nach Wahl', price: 18.00, labels: [] },
  { id: 'ta7', cat: 'Tacos', name: 'Tacos Kebab', desc: 'Kebabfleisch, Mozzarella, Pommes Frites, Sauce nach Wahl', price: 16.00, labels: ['beliebt'] },
  { id: 'ta8', cat: 'Tacos', name: 'Tacos Falafel', desc: 'Falafel (3 Stk), Mozzarella, Pommes Frites, Sauce nach Wahl', price: 16.90, labels: ['vegan'] },
  { id: 'ta9', cat: 'Tacos', name: 'Tacos Hamburger Peti', desc: 'Hamburger Patty, Mozzarella, Pommes, Peperoni, Sauce nach Wahl', price: 17.00, labels: [] },
  // ── Pizza ──
  { id: 'pz1',  cat: 'Pizza', name: 'Pizza Margherita', desc: 'Tomatensauce, Mozzarella', price: 14.00, labels: ['vegan'] },
  { id: 'pz2',  cat: 'Pizza', name: 'Wunsch Pizza (Ø32cm)', desc: 'Tomatensauce, Mozzarella, Oregano — Zutaten nach Wahl', price: 14.00, labels: [] },
  { id: 'pz3',  cat: 'Pizza', name: 'Pizza Truten Cotto', desc: 'Tomatensauce, Mozzarella, Truten, Oregano', price: 18.00, labels: [] },
  { id: 'pz4',  cat: 'Pizza', name: 'Pizza Geflügel Salami', desc: 'Tomatensauce, Mozzarella, Salami, Oregano', price: 18.00, labels: [] },
  { id: 'pz5',  cat: 'Pizza', name: 'Pizza Calzone', desc: 'Tomatensauce, Mozzarella, Schinken, Ei, Champignons', price: 18.00, labels: [] },
  { id: 'pz6',  cat: 'Pizza', name: 'Pizza Funghi', desc: 'Tomatensauce, Mozzarella, Champignons', price: 16.00, labels: ['vegan'] },
  { id: 'pz7',  cat: 'Pizza', name: 'Pizza Prosciutto', desc: 'Tomatensauce, Mozzarella, Schinken', price: 17.00, labels: [] },
  { id: 'pz8',  cat: 'Pizza', name: 'Pizza Prosciutto Funghi', desc: 'Tomatensauce, Mozzarella, Schinken, Champignons', price: 18.00, labels: [] },
  { id: 'pz9',  cat: 'Pizza', name: 'Pizza Salami', desc: 'Tomatensauce, Mozzarella, Salami', price: 17.00, labels: ['beliebt'] },
  { id: 'pz10', cat: 'Pizza', name: 'Pizza Gorgonzola', desc: 'Tomatensauce, Mozzarella, Gorgonzola', price: 16.00, labels: [] },
  { id: 'pz11', cat: 'Pizza', name: 'Pizza Tonno', desc: 'Tomatensauce, Mozzarella, Thunfisch, Zwiebeln', price: 17.00, labels: [] },
  { id: 'pz12', cat: 'Pizza', name: 'Pizza Hawaii', desc: 'Tomatensauce, Mozzarella, Schinken, Ananas', price: 18.00, labels: [] },
  { id: 'pz13', cat: 'Pizza', name: 'Pizza Frutti di Mare', desc: 'Tomatensauce, Mozzarella, Meeresfrüchte', price: 19.00, labels: [] },
  { id: 'pz14', cat: 'Pizza', name: 'Pizza Quattro Formaggi', desc: 'Tomatensauce, Mozzarella, Gorgonzola, Mascarpone, Gouda', price: 17.00, labels: [] },
  { id: 'pz15', cat: 'Pizza', name: 'Pizza Diavolo', desc: 'Tomatensauce, Mozzarella, scharfe Salami, Paprika', price: 17.00, labels: ['scharf','beliebt'] },
  { id: 'pz16', cat: 'Pizza', name: 'Kreisel Pizza', desc: 'Tomatensauce, Mozzarella, Zwiebel, Kebabfleisch', price: 17.00, labels: ['beliebt'] },
  { id: 'pz17', cat: 'Pizza', name: 'Pizza Vegetaria', desc: 'Tomatensauce, Mozzarella, saisonales Gemüse', price: 15.00, labels: ['vegan'] },
  { id: 'pz18', cat: 'Pizza', name: 'Pizza Napolitano', desc: 'Tomatensauce, Mozzarella, Kapern, Sardellen, Oliven, Oregano', price: 18.00, labels: [] },
  { id: 'pz19', cat: 'Pizza', name: 'Pizza Ranch', desc: 'Tomatensauce, Mozzarella, Schinken, Mais, Rucola, Oregano', price: 19.00, labels: [] },
  { id: 'pz20', cat: 'Pizza', name: 'Pizza Tipo Parma', desc: 'Tomatensauce, Mozzarella, Rohschinken, Oregano', price: 21.00, labels: [] },
  { id: 'pz21', cat: 'Pizza', name: 'Pizza Julia', desc: 'Tomatensauce, Mozzarella, Rohschinken, Rucola, Oregano', price: 21.00, labels: [] },
  { id: 'pz22', cat: 'Pizza', name: 'Pizza Mafiosa', desc: 'Tomatensauce, Mozzarella, Speck, Schinken, Zwiebeln, Oregano', price: 21.00, labels: [] },
  { id: 'pz23', cat: 'Pizza', name: 'Pizza Rustica', desc: 'Tomatensauce, Mozzarella, Speck, Ei, Oregano', price: 19.00, labels: [] },
  { id: 'pz24', cat: 'Pizza', name: 'Pizza Pulcinella', desc: 'Tomatensauce, Mozzarella, Speck, Salami, Sardellen, Kapern, Oregano', price: 21.00, labels: [] },
  { id: 'pz25', cat: 'Pizza', name: 'Pizza Campagnola', desc: 'Tomatensauce, Mozzarella, Champignons, Salami, Schinken, Peperoni, Oregano', price: 19.00, labels: [] },
  { id: 'pz26', cat: 'Pizza', name: 'Pizza Capri', desc: 'Tomatensauce, Mozzarella, Cherrytomaten, Zwiebeln, Rucola, Parmesan, Oregano', price: 20.00, labels: [] },
  { id: 'pz27', cat: 'Pizza', name: 'Pizza Rindfleisch Salami', desc: 'Tomatensauce, Mozzarella, Rindfleisch-Salami, Oregano', price: 18.00, labels: [] },
  { id: 'pz28', cat: 'Pizza', name: 'Vodka Pizza (18+)', desc: 'Vodka-Sauce, Mozzarella, Olivenöl, Pecorino — 0.1% vol', price: 19.00, labels: ['neu'] },
  // ── Pide ──
  { id: 'pi1', cat: 'Pide', name: 'Pide Hackfleisch', desc: 'Kalbfleisch, Peperoni, Zwiebeln, Tomaten, Petersilie', price: 23.00, labels: ['beliebt'] },
  { id: 'pi2', cat: 'Pide', name: 'Pide Fleisch', desc: 'Mozzarella, Kebabfleisch', price: 16.00, labels: [] },
  { id: 'pi3', cat: 'Pide', name: 'Pide Sucuk', desc: 'Mozzarella, Knoblauchwurst', price: 16.00, labels: ['scharf'] },
  { id: 'pi4', cat: 'Pide', name: 'Pide Spinat', desc: 'Mozzarella, Spinat, Ei', price: 16.00, labels: [] },
  { id: 'pi5', cat: 'Pide', name: 'Pide Käse', desc: 'Mozzarella, Schafskäse', price: 13.00, labels: [] },
  { id: 'pi6', cat: 'Pide', name: 'Pide Poulet', desc: 'Zubereitet mit Poulet und Zutaten nach Wahl', price: 19.00, labels: [] },
  { id: 'pi7', cat: 'Pide', name: 'Pide Italo', desc: 'Salami, Schinken, scharfe Salami', price: 19.00, labels: ['scharf'] },
  // ── Burger ──
  { id: 'bu1', cat: 'Burger', name: 'Cheeseburger', desc: 'Rindspatty (160g), Käse, Tomaten, Zwiebeln, Salat', price: 16.00, labels: ['beliebt'] },
  { id: 'bu2', cat: 'Burger', name: 'Hamburger', desc: 'Rindspatty (160g), Tomaten, Zwiebeln, Salat', price: 15.00, labels: [] },
  { id: 'bu3', cat: 'Burger', name: 'Hawaii Burger', desc: 'Rindspatty (160g), Tomaten, Zwiebeln, Salat, Ananas', price: 18.00, labels: [] },
  { id: 'bu4', cat: 'Burger', name: 'Dönburger', desc: 'Zubereitet mit Kebabfleisch', price: 16.90, labels: ['beliebt'] },
  // ── Snacks ──
  { id: 'sn1',  cat: 'Snacks', name: 'Pommes Frites', desc: 'Portion Pommes Frites', price: 9.00, labels: ['vegan'] },
  { id: 'sn2',  cat: 'Snacks', name: 'Spicy Cheese Pommes', desc: 'Pommes mit würziger Käsesauce', price: 15.00, labels: ['scharf'] },
  { id: 'sn3',  cat: 'Snacks', name: 'Garlic Kissen (9 Stk)', desc: 'Serviert mit Ranch-Sauce', price: 9.90, labels: [] },
  { id: 'sn4',  cat: 'Snacks', name: 'Kroketten (15 Stk)', desc: 'Knusprige Kroketten', price: 14.00, labels: [] },
  { id: 'sn5',  cat: 'Snacks', name: 'Frühlingsrollen (12 Stk)', desc: 'Vegetarisch', price: 16.00, labels: ['vegan'] },
  { id: 'sn6',  cat: 'Snacks', name: 'Onion Rings (8 Stk)', desc: 'Knusprige Zwiebelringe', price: 9.00, labels: ['vegan'] },
  { id: 'sn7',  cat: 'Snacks', name: 'Onion Rings (16 Stk)', desc: 'Knusprige Zwiebelringe — grosse Portion', price: 15.00, labels: ['vegan'] },
  { id: 'sn8',  cat: 'Snacks', name: 'Börek mit Spinat', desc: 'Hausgemachtes Börek', price: 11.00, labels: ['vegan'] },
  { id: 'sn9',  cat: 'Snacks', name: 'Börek mit Rindshackfleisch', desc: 'Hausgemachtes Börek', price: 11.00, labels: [] },
  { id: 'sn10', cat: 'Snacks', name: 'Börek mit Käse', desc: 'Hausgemachtes Börek', price: 11.00, labels: [] },
  { id: 'sn11', cat: 'Snacks', name: 'Chicken Nuggets (6 Stk)', desc: 'Knusprige Chicken Nuggets', price: 9.00, labels: [] },
  { id: 'sn12', cat: 'Snacks', name: 'Chicken Nuggets Box (6 Stk)', desc: 'Mit Beilage', price: 15.90, labels: [] },
  { id: 'sn13', cat: 'Snacks', name: 'Falafel Box (6 Stk)', desc: 'Mit Beilage', price: 15.90, labels: ['vegan'] },
  { id: 'sn14', cat: 'Snacks', name: 'Hot Cream Cheese Jalapeño (8 Stk)', desc: 'Gefüllte Jalapeño-Häppchen', price: 18.00, labels: ['scharf'] },
  { id: 'sn15', cat: 'Snacks', name: 'Knusprige Kartoffel Kringel', desc: 'Knusprig und würzig', price: 13.00, labels: ['vegan'] },
  { id: 'sn16', cat: 'Snacks', name: 'Potato Wedges', desc: 'Kartoffelecken', price: 13.00, labels: ['vegan'] },
  { id: 'sn17', cat: 'Snacks', name: 'Pommes Wellenschnitt', desc: 'Wellenschnitt-Pommes', price: 13.00, labels: ['vegan'] },
  { id: 'sn18', cat: 'Snacks', name: 'Mozzarella Sticks (10 Stk)', desc: 'Knusprige Mozzarella Sticks', price: 16.00, labels: [] },
  { id: 'sn19', cat: 'Snacks', name: 'Rösti Fries', desc: 'Schweizer Rösti-Fries', price: 12.50, labels: [] },
  // ── Salate ──
  { id: 'sa1', cat: 'Salate', name: 'Grüner Salat', desc: 'Mit Salatsauce nach Wahl', price: 7.00, labels: ['vegan'] },
  { id: 'sa2', cat: 'Salate', name: 'Gemischter Salat', desc: 'Gurken, Tomaten, Zwiebel, Mais — mit Salatsauce nach Wahl', price: 11.00, labels: ['vegan'] },
  { id: 'sa3', cat: 'Salate', name: 'Thon Salat', desc: 'Thunfisch, Gurken, Oliven, Tomaten, Zwiebeln', price: 13.00, labels: [] },
  { id: 'sa4', cat: 'Salate', name: 'Griechischer Salat', desc: 'Gurken, Tomaten, Käse, Oliven', price: 13.00, labels: [] },
  { id: 'sa5', cat: 'Salate', name: 'Fitness Teller', desc: 'Salat mit Poulet', price: 19.00, labels: [] },
  // ── Taschenbrot ──
  { id: 'tb1', cat: 'Taschenbrot', name: 'Pouletschnitzel im Taschenbrot', desc: 'Zubereitet mit Zutaten nach Wahl', price: 13.00, labels: [] },
  { id: 'tb2', cat: 'Taschenbrot', name: 'Poulet Cordon Bleu (Gruyère) im Taschenbrot', desc: 'Zubereitet mit Zutaten nach Wahl', price: 13.50, labels: [] },
  { id: 'tb3', cat: 'Taschenbrot', name: 'Cevapcici im Taschenbrot', desc: 'Zubereitet mit Zutaten nach Wahl', price: 14.00, labels: [] },
  { id: 'tb4', cat: 'Taschenbrot', name: 'Falafel im Taschenbrot', desc: 'Zubereitet mit Zutaten nach Wahl', price: 13.00, labels: ['vegan'] },
  { id: 'tb5', cat: 'Taschenbrot', name: 'Poulet Pepito', desc: 'Im Taschenbrot', price: 15.90, labels: ['beliebt'] },
  // ── Tellergerichte ──
  { id: 'tg1',  cat: 'Teller', name: 'Pouletschnitzel', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 18.00, labels: [] },
  { id: 'tg2',  cat: 'Teller', name: 'Poulet Cordon Bleu (Gruyère)', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 17.50, labels: [] },
  { id: 'tg3',  cat: 'Teller', name: 'Hamburger Teller', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 25.00, labels: [] },
  { id: 'tg4',  cat: 'Teller', name: 'Cevapcici (6 Stk)', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 20.00, labels: [] },
  { id: 'tg5',  cat: 'Teller', name: 'Pouletbrust', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 20.00, labels: [] },
  { id: 'tg6',  cat: 'Teller', name: 'Pouletflügeli (10 Stk)', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 20.00, labels: ['beliebt'] },
  { id: 'tg7',  cat: 'Teller', name: 'Chicken Nuggets Teller (6 Stk)', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 16.00, labels: [] },
  { id: 'tg8',  cat: 'Teller', name: 'Fisch Filet Dorsch', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 23.00, labels: [] },
  { id: 'tg9',  cat: 'Teller', name: 'Falafel Teller (8 Stk)', desc: 'Serviert mit Salat und Pommes Frites oder Kroketten', price: 16.00, labels: ['vegan'] },
  { id: 'tg10', cat: 'Teller', name: 'Poulet Pepito Teller', desc: 'Zubereitet mit Blattsalat und Sauce nach Wahl', price: 14.90, labels: [] },
  // ── Desserts ──
  { id: 'd1', cat: 'Desserts', name: 'Tiramisu', desc: 'Klassisches Tiramisu', price: 8.00, labels: ['beliebt'] },
  { id: 'd2', cat: 'Desserts', name: 'Kokos Tiramisu', desc: 'Tiramisu mit Kokosnote', price: 10.00, labels: [] },
  { id: 'd3', cat: 'Desserts', name: 'Nutella Kissen', desc: 'Warme Kissen mit Nutella-Füllung', price: 9.90, labels: ['beliebt'] },
  { id: 'd4', cat: 'Desserts', name: 'Baklava (4 Stk)', desc: 'Knuspriger Blätterteig mit Pistazienfüllung und Honigsirup', price: 8.50, labels: [] },
  { id: 'd5', cat: 'Desserts', name: 'Marlenka Cocoa (10 Stk)', desc: 'Armenische Honig-Nuggets mit Kakao — 235g', price: 15.00, labels: [] },
  { id: 'd6', cat: 'Desserts', name: 'Marlenka Honey (10 Stk)', desc: 'Armenische Honig-Nuggets — 235g', price: 15.00, labels: [] },
  { id: 'd7', cat: 'Desserts', name: 'Marlenka Torte', desc: 'Armenische Honig-Torte', price: 8.00, labels: [] },
  { id: 'd8', cat: 'Desserts', name: 'New Yorker Cheesecake', desc: 'Hausgemachter New Yorker Cheesecake', price: 10.00, labels: ['neu'] },
  // ── Getränke (alkoholfrei) ──
  { id: 'g1',  cat: 'Getränke', name: 'Coca-Cola 0.33L', desc: 'Eisgekühlt', price: 3.50, labels: [] },
  { id: 'g2',  cat: 'Getränke', name: 'Coca-Cola 0.5L', desc: 'Eisgekühlt', price: 4.00, labels: [] },
  { id: 'g3',  cat: 'Getränke', name: 'Coca-Cola Zero 0.33L', desc: 'Zuckerfrei', price: 3.50, labels: [] },
  { id: 'g4',  cat: 'Getränke', name: 'Coca-Cola Zero 0.5L', desc: 'Zuckerfrei', price: 4.00, labels: [] },
  { id: 'g5',  cat: 'Getränke', name: 'Sprite 0.33L', desc: 'Eisgekühlt', price: 3.50, labels: [] },
  { id: 'g6',  cat: 'Getränke', name: 'Sprite 0.5L', desc: 'Eisgekühlt', price: 4.00, labels: [] },
  { id: 'g7',  cat: 'Getränke', name: 'Fanta 0.33L', desc: 'Eisgekühlt', price: 3.50, labels: [] },
  { id: 'g8',  cat: 'Getränke', name: 'Fanta 0.5L', desc: 'Eisgekühlt', price: 4.00, labels: [] },
  { id: 'g9',  cat: 'Getränke', name: 'Uludag Gazoz 0.33L', desc: 'Türkisches Erfrischungsgetränk', price: 3.50, labels: [] },
  { id: 'g10', cat: 'Getränke', name: 'Uludag Gazoz 0.5L', desc: 'Türkisches Erfrischungsgetränk', price: 4.00, labels: ['beliebt'] },
  { id: 'g11', cat: 'Getränke', name: 'Fusetea Zitrone 0.5L', desc: 'Eistee mit Zitrone', price: 4.00, labels: [] },
  { id: 'g12', cat: 'Getränke', name: 'Fusetea Pfirsich 0.5L', desc: 'Eistee mit Pfirsich', price: 4.00, labels: [] },
  { id: 'g13', cat: 'Getränke', name: 'Apfelschorle 0.5L', desc: 'Apfelsaft mit Kohlensäure', price: 5.00, labels: [] },
  { id: 'g14', cat: 'Getränke', name: 'Ayran 0.33L', desc: 'Türkisches Joghurtgetränk, leicht gesalzen', price: 3.50, labels: ['beliebt'] },
  { id: 'g15', cat: 'Getränke', name: 'Mineralwasser still 0.5L', desc: 'Ohne Kohlensäure', price: 4.00, labels: ['vegan'] },
  { id: 'g16', cat: 'Getränke', name: 'Mineralwasser mit CO₂ 0.5L', desc: 'Mit Kohlensäure', price: 4.00, labels: ['vegan'] },
  { id: 'g17', cat: 'Getränke', name: 'Red Bull 0.25L', desc: 'Energy Drink', price: 5.00, labels: [] },
  { id: 'g18', cat: 'Getränke', name: 'Möhlsaft 0.5L', desc: 'Frischer Fruchtsaft ohne Alkohol', price: 6.00, labels: [] },
  // ── Alkoholische Getränke ──
  { id: 'al1', cat: 'Alkohol (18+)', name: 'Bier Lager Hell Sonnenbräu 0.5L', desc: '4.8% vol', price: 6.00, labels: [] },
  { id: 'al2', cat: 'Alkohol (18+)', name: 'Feldschlösschen 0.5L', desc: '4.8% vol', price: 5.00, labels: [] },
  { id: 'al3', cat: 'Alkohol (18+)', name: 'Chardonnay Weisswein 0.75L', desc: '13% vol', price: 25.00, labels: [] },
  { id: 'al4', cat: 'Alkohol (18+)', name: 'Bier Alkoholfrei Sonnenbräu 0.5L', desc: '0% vol', price: 6.00, labels: [] },
];

